Repository single-cell-data/TileDB-SOMA, pull requests merged in 2023-11, with the labels that each got.

#1835 [r] Update `SOMADataFrame` creation and writes
  apis/r/R/Factory.R
  apis/r/R/SOMADataFrame.R
  apis/r/R/utils-arrow.R
  apis/r/R/write_soma.R
  apis/r/man/SOMADataFrame.Rd
  apis/r/man/SOMADataFrameCreate.Rd
  apis/r/tests/testthat/test-OrderedAndFactor.R
  apis/r/tests/testthat/test-SOMADataFrame.R
Labels: backport release-1.5

#1852 [c++] Remove `spdlog` requirement
  apis/python/src/tiledbsoma/pytiledbsoma.cc
  libtiledbsoma/src/CMakeLists.txt
  libtiledbsoma/src/cli/cli.cc
  libtiledbsoma/src/soma/array_buffers.cc
  libtiledbsoma/src/soma/array_buffers.h
  libtiledbsoma/src/soma/column_buffer.cc
  libtiledbsoma/src/soma/column_buffer.h
  libtiledbsoma/src/soma/managed_query.cc
  libtiledbsoma/src/soma/managed_query.h
  libtiledbsoma/src/soma/soma_array.cc
  libtiledbsoma/src/soma/soma_array.h
  libtiledbsoma/src/utils/arrow_adapter.cc
  libtiledbsoma/src/utils/arrow_adapter.h
  libtiledbsoma/test/unit_soma_array.cc
  libtiledbsoma/test/unit_soma_group.cc
Labels: backport release-1.5

#1854 Depend on core 2.17.4, tiledb-py 0.23.4, and tiledb-r 0.21.2
  apis/python/setup.py
  apis/r/DESCRIPTION
  apis/r/tools/get_tarball.R
  libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
Labels: backport release-1.5

#1792 [python] Blockwise SciPy sparse and Arrow Table iterator
  .github/workflows/python-ci-single.yml
  apis/python/requirements_dev.txt
  apis/python/src/tiledbsoma/_read_iters.py
  apis/python/src/tiledbsoma/_sparse_nd_array.py
  apis/python/tests/test_experiment_query.py
  apis/python/tests/test_sparse_nd_array.py
Labels: backport release-1.5

#1834 [python] Handle string columns with all-NaN values
  apis/python/src/tiledbsoma/_arrow_types.py
  apis/python/tests/test_basic_anndata_io.py
Labels: backport release-1.5

#1856 [r] Set the package version to 1.5.0, and update `NEWS.md`
  apis/r/DESCRIPTION
  apis/r/NEWS.md
Labels: backport release-1.5

#1848 [c++/python] Expanded enumeration support in `ArrowAdapter::to_arrow`
  apis/python/src/tiledbsoma/_dataframe.py
  apis/python/src/tiledbsoma/pytiledbsoma.cc
  apis/python/tests/test_dataframe.py
  apis/r/src/rinterface.cpp
  apis/r/src/riterator.cpp
  libtiledbsoma/src/soma/column_buffer.h
  libtiledbsoma/src/utils/arrow_adapter.cc
  libtiledbsoma/src/utils/arrow_adapter.h
Labels: backport release-1.5

#1871 [r] No more "Last 13 lines of output:" in CI
  .github/workflows/r-ci.yml
Labels: backport release-1.5

#1876 [r] Suppress deprecation warnings in `write_soma.DataFrame()`
  apis/r/R/write_bioc.R
Labels: r-api

#1877 [python] Make Python blockwise tests less resource-intensive
  apis/python/tests/test_sparse_nd_array.py
Labels: backport release-1.5

#1863 [r] Install required tiledb package version from r-universe
  .github/workflows/r-valgrind.yaml
Labels: backport release-1.5

#1882 [r] Depend on TileDB-R 0.21.3
  apis/r/DESCRIPTION
Labels: backport release-1.5, blocks-1.5

#1884 [r] Unit-test queryability of enumerated columns
  apis/r/tests/testthat/test-SOMADataFrame.R
Labels: backport release-1.5, blocks-1.5

#1892 [python] Fix an f-string
  apis/python/src/tiledbsoma/_dataframe.py
Labels: backport release-1.5

#1898 [r] Install SeuratObject from source on macOS, rely on update r2u binary on linux
  .github/workflows/r-ci.yml
Labels: r-api

#1894 [r] Determine the R version dynamically in r-ci
  apis/r/tools/r-ci.sh
Labels: backport release-1.5

#1903 [r] Update `DESCRIPTION` to 1.5.1
  apis/r/DESCRIPTION
  apis/r/NEWS.md
Labels: backport release-1.5

#1906 [r] Restore `expect_no_condition()` tests in `Seurat` object outgestion
  .github/workflows/r-ci.yml
  apis/r/tests/testthat/test-SeuratOutgest-object.R
Labels: r-api

#1908 [python] Fix `pyarrow.compute` import for version 12
  apis/python/src/tiledbsoma/_sparse_nd_array.py
Labels: backport release-1.5

#1909 [python] Normalize unit-test exception coverage
  apis/python/tests/test_dataframe_index_columns.py
Labels: backport release-1.5

#1918 [python] Avoid a double log statement on debug-mode ingest
  apis/python/src/tiledbsoma/io/ingest.py
Labels: backport release-1.5

#1919 [python] Append-mode ingestion with disjoint measurement names
  apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
  apis/python/tests/test_registration_mappings.py
Labels: backport release-1.5

#1928 [r] Update tests
  apis/r/R/utils.R
  apis/r/R/write_soma.R
  apis/r/tests/testthat/test-SOMAArrayReader-Iterated.R
  apis/r/tests/testthat/test-SOMAOpen.R
Labels: r-api
