Repository single-cell-data/TileDB-SOMA, pull requests merged in 2024-06, with the labels that each got.

#2678 [r] Set minimum version of Arrow to 15.0.1
  apis/r/DESCRIPTION
Labels: r-api

#2685 [r] Fix dependency of a test on fixed buffer sizes
  apis/r/tests/testthat/test-SOMAArrayReader-Iterated.R
  apis/r/vignettes/soma-experiment-queries.Rmd
Labels: backport release-1.11

#2690 [r] Use `arrow` minimum 14, not 15
  apis/r/DESCRIPTION
Labels: backport release-1.11

#2695 [doc] Update README.md badge for Python CI (closes #2694) [ci skip]
  README.md
Labels: backport release-1.11

#2703 [r/ci] Unbreak `pkgdown` CI
  .github/workflows/pkgdown.yaml
  apis/r/tools/install-pkgdown-dependencies.sh
Labels: backport release-1.11

#2711 [r/ci] Unbreak `r-valgrind` CI
  .github/workflows/r-valgrind.yaml
Labels: backport release-1.11

#2723 [c++] Fix enum-of-bool leveling
  apis/python/tests/test_dataframe.py
  libtiledbsoma/src/soma/soma_array.cc
Labels: backport release-1.12

#2719 [python] Support `tiledbsoma.io.update_obs` with post-nullable non-string attributes
  apis/python/src/tiledbsoma/_arrow_types.py
  apis/python/src/tiledbsoma/io/ingest.py
  apis/python/tests/test_basic_anndata_io.py
  apis/python/tests/test_update_dataframes.py
Labels: backport release-1.12

#2745 [python] Pin to numpy < 2.0 for 1.12 release
  apis/python/setup.py
Labels: backport release-1.12

#2742 [r] Connect re-indexer to blockwise iterator
  apis/r/R/BlockwiseIter.R
  apis/r/R/SOMASparseNDArrayRead.R
  apis/r/man/BlockwiseReadIterBase.Rd
  apis/r/man/BlockwiseSparseReadIter.Rd
  apis/r/man/BlockwiseTableReadIter.Rd
  apis/r/man/IntIndexer.Rd
  apis/r/man/SOMASparseNDArrayBlockwiseRead.Rd
  apis/r/man/SOMASparseNDArrayRead.Rd
  apis/r/man/roxygen/templates/param-blockwise-iter.R
  apis/r/man/roxygen/templates/param-repr-read.R
  apis/r/tests/testthat/test-Blockwise.R
Labels: r-api, r-python-parity, backport release-1.12

#2753 [c++] Remap `TileDBError` to `TileDBSOMAError`
  libtiledbsoma/src/soma/soma_collection.cc
  libtiledbsoma/src/soma/soma_experiment.cc
  libtiledbsoma/src/soma/soma_group.cc
  libtiledbsoma/src/soma/soma_measurement.cc
Labels: backport release-1.12
