Repository single-cell-data/TileDB-SOMA, pull requests merged in 2024-05, with the labels that each got.

#2479 Remove arbitrary dimension limit in `used_shape`.
  apis/python/src/tiledbsoma/_sparse_nd_array.py
Labels: backport release-1.10

#2453 [c++] Do not add dimensions for dense array queries if not requested
  apis/r/R/SOMADenseNDArray.R
  apis/r/R/SOMAExperimentAxisQuery.R
  apis/r/tests/testthat/test-SOMADenseNDArray.R
  apis/r/tools/r-ci.sh
  apis/system/tests/test_densendarray_write_python_read_r.py
  libtiledbsoma/src/soma/managed_query.cc
  libtiledbsoma/test/unit_soma_dense_ndarray.cc
Labels: backport release-1.10

#2507 [r] Silence missing command logs warning
  apis/r/DESCRIPTION
  apis/r/NEWS.md
  apis/r/R/SOMAExperimentAxisQuery.R
  apis/r/R/utils.R
  apis/r/tests/testthat/test-SeuratOutgest-command.R
Labels: r-api

#2455 [python] Append-mode enum bit-width mods
  apis/python/src/tiledbsoma/_arrow_types.py
  apis/python/tests/test_registration_mappings.py
  apis/python/tests/test_update_dataframes.py
Labels: backport release-1.10

#2531 [r] Ensure `SOMADataFrame$shape()` throws a not-yet-implemented error
  apis/r/DESCRIPTION
  apis/r/NEWS.md
  apis/r/R/SOMADataFrame.R
  apis/r/man/SOMADataFrame.Rd
  apis/r/tests/testthat/test-SOMADataFrame.R
  apis/r/tests/testthat/test-write-soma-objects.R
Labels: r-api

#2539 [r] Suppress Warnings on SOMA -> `Seurat` Outgestion
  apis/r/DESCRIPTION
  apis/r/NEWS.md
  apis/r/R/SOMAExperimentAxisQuery.R
Labels: r-api

#2540 [r/ci] Utilize pin of tiledb-r during install
  .github/workflows/r-ci.yml
  apis/r/DESCRIPTION
  apis/r/NEWS.md
  apis/r/R/SOMAExperimentAxisQuery.R
  apis/r/tools/install-tiledb-r.R
Labels: r-api, ci

#2546 [r/ci] Add check to disable BSPM in R CI
  .github/workflows/r-ci.yml
  .github/workflows/r-python-interop-testing.yml
  apis/r/tools/install-tiledb-r.R
Labels: r-api, ci

#2561 [c++] Allow `row-major` and `col-major` in `SOMArray::create`
  libtiledbsoma/src/utils/arrow_adapter.cc
Labels: backport release-1.11

#2563 [python] Prototype: better version numbers during development
  .readthedocs.yml
  apis/python/setup.py
  apis/python/version.py
Labels: backport release-1.11

#2541 [c++] `PlatformConfig` refactoring
  apis/python/src/tiledbsoma/_util.py
  apis/python/src/tiledbsoma/options/_tiledb_create_options.py
  apis/python/src/tiledbsoma/pytiledbsoma.cc
  apis/python/src/tiledbsoma/soma_dataframe.cc
  apis/python/src/tiledbsoma/soma_dense_ndarray.cc
  apis/python/src/tiledbsoma/soma_sparse_ndarray.cc
  apis/python/tests/test_dataframe.py
  apis/python/tests/test_platform_config.py
  libtiledbsoma/src/CMakeLists.txt
  libtiledbsoma/src/external/include/nlohmann/json.hpp
  libtiledbsoma/src/soma/soma_collection.cc
  libtiledbsoma/src/soma/soma_collection.h
  libtiledbsoma/src/soma/soma_dataframe.cc
  libtiledbsoma/src/soma/soma_dataframe.h
  libtiledbsoma/src/soma/soma_dense_ndarray.cc
  libtiledbsoma/src/soma/soma_dense_ndarray.h
  libtiledbsoma/src/soma/soma_experiment.cc
  libtiledbsoma/src/soma/soma_experiment.h
  libtiledbsoma/src/soma/soma_measurement.cc
  libtiledbsoma/src/soma/soma_measurement.h
  libtiledbsoma/src/soma/soma_sparse_ndarray.cc
  libtiledbsoma/src/soma/soma_sparse_ndarray.h
  libtiledbsoma/src/utils/arrow_adapter.cc
  libtiledbsoma/src/utils/arrow_adapter.h
  libtiledbsoma/test/unit_soma_collection.cc
  libtiledbsoma/test/unit_soma_dataframe.cc
  libtiledbsoma/test/unit_soma_dense_ndarray.cc
  libtiledbsoma/test/unit_soma_sparse_ndarray.cc
Labels: backport release-1.11

#2497 [r] Better handling of timestamps in `$reopen()`
  apis/r/DESCRIPTION
  apis/r/NEWS.md
  apis/r/R/SOMADataFrame.R
  apis/r/R/TileDBGroup.R
  apis/r/R/TileDBObject.R
  apis/r/R/write_seurat.R
  apis/r/R/write_soma.R
  apis/r/man/TileDBObject.Rd
  apis/r/tests/testthat/test-SeuratIngest.R
Labels: r-api

#2594 [python/ci] Use `macos-11` -> `macos-12` for `python-packaging.yml`
  .github/workflows/python-packaging.yml
Labels: backport release-1.11

#2564 [c++/python] Enable optional global-order writes for sparse arrays
  apis/python/src/tiledbsoma/__init__.py
  apis/python/src/tiledbsoma/_dataframe.py
  apis/python/src/tiledbsoma/_sparse_nd_array.py
  apis/python/src/tiledbsoma/options/__init__.py
  apis/python/src/tiledbsoma/options/_tiledb_create_options.py
  apis/python/src/tiledbsoma/soma_array.cc
  apis/python/tests/test_sparse_nd_array.py
  libtiledbsoma/src/soma/managed_query.cc
  libtiledbsoma/src/soma/managed_query.h
  libtiledbsoma/src/soma/soma_array.cc
  libtiledbsoma/src/soma/soma_array.h
Labels: backport release-1.11

#2596 [python/c++] Typo fixes / nits
  apis/python/src/tiledbsoma/options/_tiledb_create_options.py
  apis/python/version.py
  scripts/bld
Labels: backport release-1.11

#2582 [python] Append-mode tutorial: "atlas model"
  apis/python/notebooks/tutorial_soma_append_mode.ipynb
Labels: backport release-1.11

#2491 [ci] Move Python wheel-builds from `macos-11,macos-12` to `macos-12,macos-latest`
  .github/workflows/python-packaging.yml
Labels: backport release-1.11

#2609 [c++] Fix nightly build failure on `formattable` of `json` type
  libtiledbsoma/src/utils/arrow_adapter.cc
Labels: backport release-1.11

#2626 [r] Correct four \link{} references in help pages
  apis/r/R/SOMAExperimentAxisQuery.R
  apis/r/R/utils-matrixZeroBasedView.R
  apis/r/man/SOMAExperimentAxisQuery.Rd
  apis/r/man/matrixZeroBasedView.Rd
Labels: backport release-1.11

#2637 [r] Port re-indexer to the R API
  apis/r/DESCRIPTION
  apis/r/NAMESPACE
  apis/r/NEWS.md
  apis/r/R/IntIndexer.R
  apis/r/R/RcppExports.R
  apis/r/man/IntIndexer.Rd
  apis/r/src/RcppExports.cpp
  apis/r/src/reindexer.cpp
  apis/r/src/rinterface.cpp
  apis/r/src/riterator.cpp
  apis/r/src/rutilities.cpp
  apis/r/src/xptr-utils.h
  apis/r/tests/testthat/test-IntIndexer.R
Labels: r-api

#2645 [c++] Pass in a `shared_ptr<Context>` to `_create_dim_aux`
  libtiledbsoma/src/utils/arrow_adapter.cc
  libtiledbsoma/src/utils/arrow_adapter.h
Labels: backport release-1.11

#2649 [r/ci] Adjust file download timeout to 300 seconds
  .github/workflows/r-ci.yml
  apis/r/tests/testthat/test-SingleCellExperimentIngest.R
  apis/r/tests/testthat/test-SummarizedExperimentIngest.R
  apis/r/tests/testthat/test-write-soma-resume.R
Labels: r-api, ci, backport release-1.11

#2665 [c++] Fix indexer memory leak
  apis/python/src/tiledbsoma/reindexer.cc
  apis/python/src/tiledbsoma/soma_array.cc
  apis/python/src/tiledbsoma/soma_dataframe.cc
  apis/python/src/tiledbsoma/soma_dense_ndarray.cc
  apis/python/src/tiledbsoma/soma_sparse_ndarray.cc
Labels: backport release-1.11
