Repository single-cell-data/TileDB-SOMA, pull requests merged in 2024-02, with the labels that each got.

#2087 [r] Let `get_tarball.R` interop with `update-tiledb-version.py`
  apis/r/tools/get_tarball.R
Labels: backport release-1.7

#2082 [python] Do not mutate `adata.obs`/`adata.var` on ingest
  apis/python/src/tiledbsoma/_util.py
  apis/python/src/tiledbsoma/io/_registration/signatures.py
  apis/python/src/tiledbsoma/io/conversions.py
  apis/python/src/tiledbsoma/io/ingest.py
  apis/python/tests/test_basic_anndata_io.py
  apis/python/tests/test_platform_config.py
  apis/python/tests/test_registration_mappings.py
  apis/python/tests/test_registration_signatures.py
  apis/python/tests/test_update_dataframes.py
Labels: backport release-1.7

#2083 [python] Specially handle cast for object and category dtypes
  apis/python/src/tiledbsoma/_arrow_types.py
  apis/python/tests/test_basic_anndata_io.py
Labels: backport release-1.7

#2024 [r] Support outgestion of `SeuratCommands`
  apis/r/DESCRIPTION
  apis/r/NAMESPACE
  apis/r/NEWS.md
  apis/r/R/SOMAExperimentAxisQuery.R
  apis/r/R/utils-assertions.R
  apis/r/R/utils-seurat.R
  apis/r/R/utils.R
  apis/r/tests/testthat/test-SeuratOutgest-command.R
Labels: r-api

#2106 [Backport release-1.7] [r] Support ingestion of `SeuratCommands`
  apis/r/DESCRIPTION
  apis/r/NAMESPACE
  apis/r/NEWS.md
  apis/r/R/utils.R
  apis/r/R/write_seurat.R
  apis/r/R/write_soma.R
  apis/r/man/write_soma.Seurat.Rd
  apis/r/man/write_soma_seurat_sub.Rd
  apis/r/tests/testthat/test-SeuratIngest.R
Labels: backport release-1.7

#2110 [python] Reorganize `Reindexer` bindings into separate file
  apis/python/setup.py
  apis/python/src/tiledbsoma/pytiledbsoma.cc
  apis/python/src/tiledbsoma/reindexer.cc
Labels: backport release-1.7

#2140 [python/ci] Leave 3.12 support provisional
  .github/workflows/python-ci-full.yml
  .github/workflows/python-ci-minimal.yml
Labels: backport release-1.7, for-1.7.1

#2139 [python] Lint fix
  apis/python/tests/test_basic_anndata_io.py
Labels: backport release-1.7

#2119 [python] Outgest additional X layers to AnnData
  apis/python/src/tiledbsoma/io/ingest.py
  apis/python/tests/test_basic_anndata_io.py
Labels: backport release-1.7, for-1.7.1

#2138 [Backport release-1.7] [python] Add type checks to `obsm`, `obsp`, `varm` and `varp` early in ingestion
  apis/python/src/tiledbsoma/io/ingest.py
  apis/python/tests/test_basic_anndata_io.py
Labels: for-1.7.1

#2144 [Backport release-1.7] [python] Outgest additional X layers to AnnData
  apis/python/src/tiledbsoma/io/ingest.py
  apis/python/tests/test_basic_anndata_io.py
Labels: for-1.7.1

#2154 [r] Fix Seurat ingestion with missing command logs collection
  apis/r/DESCRIPTION
  apis/r/R/SOMAExperimentAxisQuery.R
  apis/r/R/utils-seurat.R
  apis/r/R/utils.R
  apis/r/tests/testthat/test-SeuratOutgest-command.R
Labels: r-api, backport release-1.7

#2175 [python] Expose `tiledbsoma.io.ExperimentAmbientLabelMapping`
  apis/python/src/tiledbsoma/io/__init__.py
  apis/python/tests/test_registration_mappings.py
Labels: backport release-1.7, backport release-1.8
