Repository single-cell-data/TileDB-SOMA, pull requests merged in 2024-01, with the labels that each got.

#1999 [python] Minor update to `from_h5ad` online help
  apis/python/src/tiledbsoma/io/ingest.py
Labels: backport release-1.5

#2013 [r] Add support for registering arrays with `write_soma()`
  apis/r/DESCRIPTION
  apis/r/NEWS.md
  apis/r/R/write_soma.R
  apis/r/man/write_soma_objects.Rd
  apis/r/tests/testthat/test-write-soma-objects.R
Labels: r-api

#2021 [r] Add `write_soma.character()`
  apis/r/DESCRIPTION
  apis/r/NAMESPACE
  apis/r/NEWS.md
  apis/r/R/utils.R
  apis/r/R/write_soma.R
  apis/r/man/write_soma_objects.Rd
  apis/r/tests/testthat/test-write-soma-objects.R
Labels: r-api

#2048 [c++/ci] Fix a `pkgdown` CI error about unnecessary semicolons
  libtiledbsoma/src/soma/soma_array.h
  libtiledbsoma/src/soma/soma_dataframe.h
  libtiledbsoma/src/soma/soma_dense_ndarray.h
  libtiledbsoma/src/soma/soma_sparse_ndarray.h
  libtiledbsoma/src/utils/common.h
Labels: backport release-1.7

#2057 [python] Rename `utils.py` to `_index_util.py`
  apis/python/src/tiledbsoma/_experiment.py
  apis/python/src/tiledbsoma/_index_util.py
  apis/python/tests/test_indexer.py
Labels: backport release-1.7

#2049 [python] Pass config options to `DataFrame.read`
  apis/python/src/tiledbsoma/_dataframe.py
  apis/python/src/tiledbsoma/soma_dataframe.cc
  libtiledbsoma/src/soma/soma_array.cc
  libtiledbsoma/src/soma/soma_array.h
  libtiledbsoma/src/soma/soma_dataframe.cc
  libtiledbsoma/src/soma/soma_dataframe.h
Labels: backport release-1.7

#2026 [python] Chunked writes for DataFrame; byte-caps for Arrow-table writes
  apis/python/src/tiledbsoma/io/ingest.py
  apis/python/src/tiledbsoma/options/_tiledb_create_options.py
  apis/python/tests/test_io.py
Labels: backport release-1.6, backport release-1.7

#2023 [r] Support Ingestion of `SeuratCommands`
  apis/r/DESCRIPTION
  apis/r/NAMESPACE
  apis/r/NEWS.md
  apis/r/R/utils.R
  apis/r/R/write_seurat.R
  apis/r/R/write_soma.R
  apis/r/man/write_soma.Seurat.Rd
  apis/r/man/write_soma_seurat_sub.Rd
  apis/r/tests/testthat/test-SeuratIngest.R
Labels: r-api

#2069 [python] Silence a unit-test warning
  apis/python/src/tiledbsoma/io/conversions.py
Labels: backport release-1.7

#2028 [python] Save off ingest-time obs/var index names for use at outgest
  apis/python/devtools/outgestor
  apis/python/src/tiledbsoma/io/ingest.py
  apis/python/tests/test_basic_anndata_io.py
Labels: backport release-1.7

#2084 Use core 2.19.1
  apis/r/tools/get_tarball.R
  libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
  scripts/update-tiledb-version.py
Labels: backport release-1.7

#2088 [python] Elaborate docstring re relativity for add-new
  apis/python/src/tiledbsoma/_collection.py
Labels: backport release-1.7

#2081 [python] Using optimized reindexer in blockwise iterators
  apis/python/src/tiledbsoma/_read_iters.py
  apis/python/src/tiledbsoma/_sparse_nd_array.py
Labels: backport release-1.7

#2094 [python] Fix some docstring typos
  apis/python/src/tiledbsoma/_index_util.py
Labels: backport release-1.7

#2096 [c++] Fix for error when the key array size is smaller than thread count
  apis/python/tests/test_indexer.py
  libtiledbsoma/src/reindexer/reindexer.cc
Labels: backport release-1.7
