Repository single-cell-data/TileDB-SOMA, pull requests merged in 2024-04, with the labels that each got.

#2357 [python] Skip writing empty `arrow_table`s
  apis/python/src/tiledbsoma/_arrow_types.py
  apis/python/src/tiledbsoma/io/ingest.py
  apis/python/tests/test_basic_anndata_io.py
Labels: backport release-1.9

#2360 [python] `tiledbsoma.io.from_h5ad`: document new `additional_metadata` param
  apis/python/src/tiledbsoma/io/ingest.py
Labels: backport release-1.9

#2369 [python] Expand coverage for registration of multi-region S3-backed H5ADs
  apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
Labels: backport release-1.9

#2366 [c++] Set `nanoarrow.c` to use `CMAKE_CXX_COMPILER`
  apis/r/src/borrowed.c
  libtiledbsoma/src/CMakeLists.txt
Labels: backport release-1.9

#2376 [r] Additional `nanoarrow` refactor followup
  apis/r/src/borrowed.c
  apis/r/src/rinterface.cpp
  apis/r/src/riterator.cpp
  apis/r/src/rutilities.cpp
Labels: backport release-1.9

#2152 [r] Port blockwise iterator/reader to R
  apis/r/DESCRIPTION
  apis/r/NAMESPACE
  apis/r/NEWS.md
  apis/r/R/BlockwiseIter.R
  apis/r/R/CoordsStrider.R
  apis/r/R/RcppExports.R
  apis/r/R/ReadIter.R
  apis/r/R/SOMASparseNDArray.R
  apis/r/R/SOMASparseNDArrayRead.R
  apis/r/R/SparseReadIter.R
  apis/r/R/TableReadIter.R
  apis/r/R/utils-readerTransformers.R
  apis/r/man/BlockwiseReadIterBase.Rd
  apis/r/man/BlockwiseSparseReadIter.Rd
  apis/r/man/BlockwiseTableReadIter.Rd
  apis/r/man/CoordsStrider.Rd
  apis/r/man/SOMASparseNDArrayBlockwiseRead.Rd
  apis/r/man/SOMASparseNDArrayRead.Rd
  apis/r/man/SOMASparseNDArrayReadBase.Rd
  apis/r/man/roxygen/templates/param-blockwise-iter.R
  apis/r/man/roxygen/templates/param-coords-iter.R
  apis/r/man/roxygen/templates/param-coords-read.R
  apis/r/man/roxygen/templates/param-repr-read.R
  apis/r/src/RcppExports.cpp
  apis/r/src/riterator.cpp
  apis/r/tests/testthat/test-Blockwise.R
  apis/r/tests/testthat/test-CoordsStrider.R
Labels: r-api

#2381 [python] `isort`: `tiledbsoma` before `tiledb`
  .pre-commit-config.yaml
  apis/python/devtools/desc-array-fragments
  apis/python/devtools/ingestor
  apis/python/devtools/outgestor
  apis/python/devtools/peek-exp.py
  apis/python/pyproject.toml
  apis/python/src/tiledbsoma/_arrow_types.py
  apis/python/src/tiledbsoma/_collection.py
  apis/python/src/tiledbsoma/_common_nd_array.py
  apis/python/src/tiledbsoma/_dataframe.py
  apis/python/src/tiledbsoma/_sparse_nd_array.py
  apis/python/src/tiledbsoma/_tdb_handles.py
  apis/python/src/tiledbsoma/_tiledb_array.py
  apis/python/src/tiledbsoma/_tiledb_object.py
  apis/python/src/tiledbsoma/io/_util.py
  apis/python/src/tiledbsoma/io/ingest.py
  apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
  apis/python/src/tiledbsoma/options/_tiledb_create_options.py
  apis/python/tests/test_basic_anndata_io.py
  apis/python/tests/test_collection.py
  apis/python/tests/test_context.py
  apis/python/tests/test_dataframe.py
  apis/python/tests/test_dataframe_index_columns.py
  apis/python/tests/test_dense_nd_array.py
  apis/python/tests/test_experiment_query.py
  apis/python/tests/test_factory.py
  apis/python/tests/test_metadata.py
  apis/python/tests/test_notebook_sparse_dense.py
  apis/python/tests/test_platform_config.py
  apis/python/tests/test_query_condition.py
  apis/python/tests/test_sparse_nd_array.py
  apis/python/tests/test_tiledbobject.py
  apis/python/tests/test_util_tiledb.py
  data/simple/ij_test1/gen.py
  scripts/show-versions.py
Labels: backport release-1.9

#2380 [python] Check for uniqueness of registration obs/var field-name inputs
  apis/python/src/tiledbsoma/io/_registration/id_mappings.py
  apis/python/tests/test_registration_mappings.py
Labels: backport release-1.9

#2384 [python] Enforce if-not-exists semantics for append/registration
  apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
  apis/python/tests/test_registration_mappings.py
Labels: backport release-1.9

#2398 [r/ci] Unbreak wheel builds
  libtiledbsoma/src/external/src/nanoarrow/nanoarrow.c
Labels: backport release-1.9

#2372 [r] Add `$reopen()` to `TileDBObject`
  apis/r/DESCRIPTION
  apis/r/NEWS.md
  apis/r/R/SOMADataFrame.R
  apis/r/R/TileDBArray.R
  apis/r/R/TileDBObject.R
  apis/r/man/EphemeralCollection.Rd
  apis/r/man/EphemeralCollectionBase.Rd
  apis/r/man/EphemeralExperiment.Rd
  apis/r/man/EphemeralMeasurement.Rd
  apis/r/man/SOMAArrayBase.Rd
  apis/r/man/SOMACollection.Rd
  apis/r/man/SOMACollectionBase.Rd
  apis/r/man/SOMADataFrame.Rd
  apis/r/man/SOMADenseNDArray.Rd
  apis/r/man/SOMAExperiment.Rd
  apis/r/man/SOMAMeasurement.Rd
  apis/r/man/SOMANDArrayBase.Rd
  apis/r/man/SOMASparseNDArray.Rd
  apis/r/man/TileDBArray.Rd
  apis/r/man/TileDBGroup.Rd
  apis/r/man/TileDBObject.Rd
  apis/r/tests/testthat/test-SeuratIngest.R
  apis/r/tests/testthat/test-reopen.R
Labels: r-api

#2435 Run SO copying workflow on macos-13 to avoid SIP
  .github/workflows/python-so-copying.yml
Labels: backport release-1.9

#2441 [python] Code-review-feedback follow-up from #2434
  apis/python/src/tiledbsoma/io/ingest.py
Labels: backport release-1.9

#2437 [python] `verify_core_versions()` during `import tiledbsoma`
  apis/python/src/tiledbsoma/__init__.py
  apis/python/src/tiledbsoma/_general_utilities.py
Labels: backport release-1.9

#2457 [python]Robust URI handling for Ingestion-performance improvement
  apis/python/src/tiledbsoma/__init__.py
  apis/python/src/tiledbsoma/_collection.py
  apis/python/src/tiledbsoma/_common_nd_array.py
  apis/python/src/tiledbsoma/_dataframe.py
  apis/python/src/tiledbsoma/_exception.py
  apis/python/src/tiledbsoma/io/ingest.py
Labels: backport release-1.10

#2475 [r,ci] Update `r-ci.sh`, remove unneeded entries from `r-ci.yml`
  .github/workflows/r-ci.yml
  apis/r/tools/r-ci.sh
Labels: backport release-1.10

#2476 [python] Allow `obs_query=None`/`var_query=None` in `ExperimentAxisQuery`
  .pre-commit-config.yaml
  apis/python/setup.py
  apis/python/tests/test_experiment_query.py
Labels: backport release-1.10

#2405 [r] Port resume-mode to R
  apis/r/DESCRIPTION
  apis/r/NAMESPACE
  apis/r/NEWS.md
  apis/r/R/Factory.R
  apis/r/R/TileDBObject.R
  apis/r/R/utils.R
  apis/r/R/write_bioc.R
  apis/r/R/write_seurat.R
  apis/r/R/write_soma.R
  apis/r/man/SOMACollectionCreate.Rd
  apis/r/man/SOMACollectionOpen.Rd
  apis/r/man/SOMADataFrameCreate.Rd
  apis/r/man/SOMADataFrameOpen.Rd
  apis/r/man/SOMADenseNDArrayOpen.Rd
  apis/r/man/SOMAExperimentCreate.Rd
  apis/r/man/SOMAExperimentOpen.Rd
  apis/r/man/SOMAMeasurementCreate.Rd
  apis/r/man/SOMAMeasurementOpen.Rd
  apis/r/man/SOMASparseNDArrayCreate.Rd
  apis/r/man/SOMASparseNDArrayOpen.Rd
  apis/r/man/TileDBObject.Rd
  apis/r/man/write_soma.Seurat.Rd
  apis/r/man/write_soma.SingleCellExperiment.Rd
  apis/r/man/write_soma.SummarizedExperiment.Rd
  apis/r/man/write_soma_objects.Rd
  apis/r/man/write_soma_seurat_sub.Rd
  apis/r/tests/testthat/test-SeuratIngest.R
  apis/r/tests/testthat/test-write-soma-objects.R
  apis/r/tests/testthat/test-write-soma-resume.R
Labels: r-api, r-python-parity

#2483 [r] Set default create options during `TileDBCreateOptions$new()`
  apis/r/DESCRIPTION
  apis/r/NEWS.md
  apis/r/R/TileDBCreateOptions.R
  apis/r/man/TileDBCreateOptions.Rd
  apis/r/tests/testthat/test-TileDBCreateOptions.R
Labels: r-api

#2486 [r] Always return filters in `TileDBCreateOptions`
  apis/r/DESCRIPTION
  apis/r/R/TileDBCreateOptions.R
Labels: r-api
