Repository single-cell-data/TileDB-SOMA, pull requests merged in 2024-11, with the labels that each got.

#2523 [r] Add initial support for ragged array writing for Seurat v5
  apis/r/DESCRIPTION
  apis/r/NAMESPACE
  apis/r/NEWS.md
  apis/r/R/SOMADataFrame.R
  apis/r/R/utils-seurat.R
  apis/r/R/utils.R
  apis/r/R/write_seurat.R
  apis/r/man/write_soma.Seurat.Rd
  apis/r/man/write_soma_seurat_sub.Rd
  apis/r/tests/testthat/test-SeuratIngest.R
Labels: r-api

#3319 [r/ci] Remove tiledb-r specific install
  .github/workflows/pkgdown.yaml
  .github/workflows/r-ci.yml
  .github/workflows/r-python-interop-testing.yml
  .github/workflows/r-valgrind.yaml
Labels: r-api, ci

#3326 [python] Run `pre-commit autoupdate`
  .pre-commit-config.yaml
  apis/python/notebooks/tutorial_exp_query.ipynb
  apis/python/notebooks/tutorial_soma_append_mode.ipynb
  apis/python/notebooks/tutorial_soma_objects.ipynb
  apis/python/notebooks/tutorial_soma_reading.ipynb
  apis/python/notebooks/tutorial_soma_shape.ipynb
  apis/python/notebooks/tutorial_spatial.ipynb
  apis/python/src/tiledbsoma/_util.py
Labels: for-release-1.15

#3304 [python/c++] COO to CSX conversion optimization
  .github/workflows/r-python-interop-testing.yml
  apis/python/setup.py
  apis/python/src/tiledbsoma/_fastercsx.py
  apis/python/src/tiledbsoma/_read_iters.py
  apis/python/src/tiledbsoma/fastercsx.cc
  apis/python/src/tiledbsoma/io/conversions.py
  apis/python/src/tiledbsoma/io/outgest.py
  apis/python/src/tiledbsoma/pytiledbsoma.cc
  apis/python/tests/_util.py
  apis/python/tests/test_fastercsx.py
  apis/python/tests/test_libfastercsx.py
  libtiledbsoma/src/CMakeLists.txt
  libtiledbsoma/src/external/include/thread_pool/producer_consumer_queue.h
  libtiledbsoma/src/external/include/thread_pool/thread_pool.h
  libtiledbsoma/src/external/src/thread_pool/thread_pool.cc
  libtiledbsoma/src/utils/fastercsx.h
  libtiledbsoma/src/utils/parallel_functions.h
Labels: for-release-1.15

#3328 [python] Partition sparse matrix reads in `tiledbsoma.io.to_anndata`
  apis/python/src/tiledbsoma/io/outgest.py
Labels: for-release-1.15

#3307 [python] Ingest `somacore` classes
  .pre-commit-config.yaml
  apis/python/setup.py
  apis/python/src/tiledbsoma/_dataframe.py
  apis/python/src/tiledbsoma/_eager_iter.py
  apis/python/src/tiledbsoma/_experiment.py
  apis/python/src/tiledbsoma/_fast_csr.py
  apis/python/src/tiledbsoma/_fastercsx.py
  apis/python/src/tiledbsoma/_indexer.py
  apis/python/src/tiledbsoma/_query.py
  apis/python/src/tiledbsoma/_read_iters.py
  apis/python/src/tiledbsoma/_types.py
  apis/python/src/tiledbsoma/_util.py
  apis/python/src/tiledbsoma/experimental/_xarray_backend.py
  apis/python/src/tiledbsoma/experimental/ingest.py
  apis/python/tests/test_eager_iter.py
  apis/python/tests/test_experiment_query.py
Labels: for-release-1.15

#3381 [python] Fix typos and import order in the spatial outgest
  apis/python/src/tiledbsoma/experimental/_xarray_backend.py
  apis/python/src/tiledbsoma/experimental/outgest.py
Labels: backport release-1.15
