Repository single-cell-data/TileDB-SOMA, pull requests merged in 2024-12, with the labels that each got.

#3302 [r] Vignette for new-shape feature
  apis/python/notebooks/tutorial_soma_shape.ipynb
  apis/r/DESCRIPTION
  apis/r/NEWS.md
  apis/r/R/datasets.R
  apis/r/_pkgdown.yml
  apis/r/inst/extdata/soma-exp-pbmc-small-pre-1.15.tar.gz
  apis/r/vignettes/soma-shapes.Rmd
Labels: blocker, for-release-1.15

#3395 [r] Adjust blockwise + re-indexer to return condensed matrix, not full domain
  apis/r/R/BlockwiseIter.R
  apis/r/tests/testthat/test-00-Blockwise.R
Labels: r-api

#3401 [r] Update changelog and develop version for #3395
  apis/r/DESCRIPTION
  apis/r/NEWS.md
Labels: r-api

#3293 [python] Remove double open For `SOMAArray` reads
  apis/python/src/tiledbsoma/_dataframe.py
  apis/python/src/tiledbsoma/_dense_nd_array.py
  apis/python/src/tiledbsoma/_point_cloud_dataframe.py
  apis/python/src/tiledbsoma/_read_iters.py
  apis/python/src/tiledbsoma/_sparse_nd_array.py
  apis/python/src/tiledbsoma/_util.py
  apis/python/src/tiledbsoma/managed_query.cc
  apis/python/tests/test_dataframe.py
  apis/python/tests/test_dense_nd_array.py
  apis/python/tests/test_sparse_nd_array.py
  libtiledbsoma/src/soma/managed_query.cc
  libtiledbsoma/src/soma/managed_query.h
Labels: for-release-1.15

#3410 [c++] Use core 2.27.0.rc5
  .github/workflows/python-ci-packaging.yml
  apis/r/tools/get_tarball.R
  libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
Labels: for-release-1.15

#3416 [c++] Fix upgrade-soma-joinid-shape for dataframes having non-standard dimensions
  apis/python/testdata/nonstandard-dataframe-without-shapes.tgz
  apis/python/tests/test_shape.py
  libtiledbsoma/src/soma/soma_array.cc
Labels: backport release-1.15

#3418 [c++] `ManagedQuery::set_condition` should not reset entire instance state
  apis/python/src/tiledbsoma/managed_query.cc
  libtiledbsoma/src/soma/managed_query.cc
  libtiledbsoma/src/soma/managed_query.h
Labels: backport release-1.15

#3421 [c++] Use core 2.27.0
  .github/workflows/python-ci-packaging.yml
  apis/r/tools/get_tarball.R
  libtiledbsoma/cmake/Modules/FindTileDB_EP.cmake
Labels: backport release-1.15, for-release-1.15

#3402 [python, c++] Fix misleading `DoesNotExistErrors` in `open` factory
  apis/python/src/tiledbsoma/_collection.py
  apis/python/src/tiledbsoma/_exception.py
  apis/python/src/tiledbsoma/_soma_array.py
  apis/python/src/tiledbsoma/_soma_object.py
  apis/python/src/tiledbsoma/_tdb_handles.py
  apis/python/src/tiledbsoma/soma_collection.cc
  apis/python/src/tiledbsoma/soma_object.cc
  apis/python/tests/test_collection.py
  apis/python/tests/test_dataframe.py
  apis/python/tests/test_dense_nd_array.py
  apis/python/tests/test_experiment_basic.py
  apis/python/tests/test_multiscale_image.py
  apis/python/tests/test_platform_config.py
  apis/python/tests/test_point_cloud_dataframe.py
  apis/python/tests/test_scene.py
  apis/python/tests/test_sparse_nd_array.py
  apis/r/src/rinterface.cpp
  libtiledbsoma/src/soma/soma_array.cc
  libtiledbsoma/src/soma/soma_array.h
  libtiledbsoma/src/soma/soma_collection.cc
  libtiledbsoma/src/soma/soma_dataframe.cc
  libtiledbsoma/src/soma/soma_dense_ndarray.cc
  libtiledbsoma/src/soma/soma_experiment.cc
  libtiledbsoma/src/soma/soma_measurement.cc
  libtiledbsoma/src/soma/soma_multiscale_image.cc
  libtiledbsoma/src/soma/soma_object.cc
  libtiledbsoma/src/soma/soma_object.h
  libtiledbsoma/src/soma/soma_point_cloud_dataframe.cc
  libtiledbsoma/src/soma/soma_scene.cc
  libtiledbsoma/src/soma/soma_sparse_ndarray.cc
  libtiledbsoma/test/unit_soma_dataframe.cc
  libtiledbsoma/test/unit_soma_dense_ndarray.cc
  libtiledbsoma/test/unit_soma_sparse_ndarray.cc
Labels: backport release-1.15

#3409 [python] Export full experiment to SpatialData
  apis/python/src/tiledbsoma/io/spatial/__init__.py
  apis/python/src/tiledbsoma/io/spatial/outgest.py
  apis/python/tests/test_basic_spatialdata_io.py
Labels: backport release-1.15

#3439 [c++] Match zero-basing for old/new sparse-array shapes
  libtiledbsoma/src/soma/soma_array.cc
  libtiledbsoma/src/soma/soma_array.h
Labels: backport release-1.15

#3445 [python] Pre-emptively avoid SciPy 1.15, pending a bugfix
  apis/python/setup.py
Labels: backport release-1.15

#3449 [python] Rename `to_spatial_data` -> `to_spatialdata`
  apis/python/src/tiledbsoma/_query.py
  apis/python/src/tiledbsoma/io/spatial/__init__.py
  apis/python/src/tiledbsoma/io/spatial/outgest.py
  apis/python/tests/test_basic_spatialdata_io.py
  apis/python/tests/test_experiment_query_spatial.py
  apis/python/tests/test_export_multiscale_image.py
  apis/python/tests/test_export_point_cloud_dataframe.py
  apis/python/tests/test_spatial_outgest_util.py
Labels: backport release-1.15

#3446 [python] Fix conditional fall-through in `SOMAObject.open`
  apis/python/src/tiledbsoma/soma_object.cc
Labels: backport release-1.15

#3455 [python] Use `somacore` 1.0.25
  .pre-commit-config.yaml
  apis/python/setup.py
Labels: backport release-1.15

#3460 [python] Use `somacore` 1.0.26
  .pre-commit-config.yaml
  apis/python/setup.py
Labels: backport release-1.15

#3456 [python/c++] Fix invalid memory read in `fastercsx`
  apis/python/src/tiledbsoma/fastercsx.cc
  apis/python/tests/test_libfastercsx.py
  libtiledbsoma/src/utils/fastercsx.h
Labels: backport release-1.15

#3453 [python] Convert from `Optional[Foo]` to `Foo | None`
  apis/python/setup.py
  apis/python/src/tiledbsoma/_collection.py
  apis/python/src/tiledbsoma/_common_nd_array.py
  apis/python/src/tiledbsoma/_dataframe.py
  apis/python/src/tiledbsoma/_dense_nd_array.py
  apis/python/src/tiledbsoma/_eager_iter.py
  apis/python/src/tiledbsoma/_experiment.py
  apis/python/src/tiledbsoma/_factory.py
  apis/python/src/tiledbsoma/_geometry_dataframe.py
  apis/python/src/tiledbsoma/_indexer.py
  apis/python/src/tiledbsoma/_multiscale_image.py
  apis/python/src/tiledbsoma/_point_cloud_dataframe.py
  apis/python/src/tiledbsoma/_query.py
  apis/python/src/tiledbsoma/_query_condition.py
  apis/python/src/tiledbsoma/_read_iters.py
  apis/python/src/tiledbsoma/_scene.py
  apis/python/src/tiledbsoma/_soma_group.py
  apis/python/src/tiledbsoma/_soma_object.py
  apis/python/src/tiledbsoma/_sparse_nd_array.py
  apis/python/src/tiledbsoma/_spatial_dataframe.py
  apis/python/src/tiledbsoma/_spatial_util.py
  apis/python/src/tiledbsoma/_tdb_handles.py
  apis/python/src/tiledbsoma/_util.py
  apis/python/src/tiledbsoma/io/_common.py
  apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
  apis/python/src/tiledbsoma/io/_registration/signatures.py
  apis/python/src/tiledbsoma/io/_util.py
  apis/python/src/tiledbsoma/io/ingest.py
  apis/python/src/tiledbsoma/io/outgest.py
  apis/python/src/tiledbsoma/io/shaping.py
  apis/python/src/tiledbsoma/io/spatial/_xarray_backend.py
  apis/python/src/tiledbsoma/io/spatial/ingest.py
  apis/python/src/tiledbsoma/io/spatial/outgest.py
  apis/python/src/tiledbsoma/io/update_uns.py
  apis/python/src/tiledbsoma/logging.py
  apis/python/src/tiledbsoma/options/_tiledb_create_write_options.py
  apis/python/tests/_util.py
  apis/python/tests/test_basic_anndata_io.py
  apis/python/tests/test_dataframe_io_roundtrips.py
  apis/python/tests/test_registration_mappings.py
  apis/python/tests/test_reindexer_api.py
  apis/python/tests/test_update_dataframes.py
  apis/python/tests/test_update_uns.py
  apis/python/version.py
Labels: python-api

#3466 [docs] Fix broken tutorial-doc symlinks in `release-1.15`
  doc/source/notebooks/tutorial_soma_shape.ipynb
  doc/source/notebooks/tutorial_spatial.ipynb
Labels: backport release-1.15

#3469 [r] Write group-level string metadata as `TILEDB_STRING_UTF8`
  apis/r/DESCRIPTION
  apis/r/NEWS.md
  apis/r/src/groups.cpp
  apis/system/tests/test_character_write_python_read_r.py
  apis/system/tests/test_character_write_r_read_python.py
Labels: r-api, r-python-parity, backport release-1.15

#3476 [python] Re-enable `tiledbsoma.ExperimentAxisQuery`
  apis/python/src/tiledbsoma/__init__.py
  apis/python/src/tiledbsoma/_query.py
  apis/python/tests/test_experiment_query.py
Labels: backport release-1.15

#3468 [c++, python] `fastercsx`: improved duplicate coordinate handling
  apis/python/src/tiledbsoma/_fastercsx.py
  apis/python/src/tiledbsoma/fastercsx.cc
  apis/python/tests/test_fastercsx.py
  apis/python/tests/test_libfastercsx.py
  libtiledbsoma/src/utils/fastercsx.h
Labels: backport release-1.15

#3473 [python] Fix a test deprecation warning
  apis/python/tests/test_basic_anndata_io.py
Labels: backport release-1.15

#3463 [c++] Set overriding user-provided prefix to be off by default
  libtiledbsoma/CMakeLists.txt
  scripts/bld
  scripts/bld.ps1
Labels: backport release-1.15

#3490 [python] Filter spatial disclaimer from pytest
  apis/python/pyproject.toml
Labels: backport release-1.15

#3495 [python] `tiledbsoma.__init__.py`: restore lint checks
  apis/python/src/tiledbsoma/__init__.py
Labels: backport release-1.15

#3491 [python] Update `add_new_collection` method to support `Scene` collections
  apis/python/src/tiledbsoma/_collection.py
  apis/python/tests/test_basic_spatialdata_io.py
  apis/python/tests/test_experiment_query_spatial.py
Labels: backport release-1.15
