Repository single-cell-data/TileDB-SOMA, pull requests merged in 2024-08, with the labels that each got.

#2825 [r] Add `drop_levels` to `SOMAExperimentAxisQuery` -> ecosystem outgestors
  apis/r/DESCRIPTION
  apis/r/NEWS.md
  apis/r/R/SOMAExperimentAxisQuery.R
  apis/r/man/SOMAExperimentAxisQuery.Rd
  apis/r/tests/testthat/helper-test-data.R
  apis/r/tests/testthat/helper-test-soma-objects.R
  apis/r/tests/testthat/test-SCEOutgest.R
  apis/r/tests/testthat/test-SeuratOutgest-assay.R
  apis/r/tests/testthat/test-SeuratOutgest-object.R
Labels: r-api, r-python-parity

#2842 [python] Implement scheduled removal of `TileDBCreateOptions` being passed to `write` methods
  apis/python/src/tiledbsoma/_dataframe.py
  apis/python/src/tiledbsoma/_sparse_nd_array.py
  apis/python/tests/test_sparse_nd_array.py
Labels: backport release-1.13

#2814 [python] Use original error message when re-raising with `DoesNotExistError`
  apis/python/src/tiledbsoma/_collection.py
  apis/python/src/tiledbsoma/_tdb_handles.py
Labels: backport release-1.13

#2838 [python] Debug CI `mypy` failures related to `# type: ignore[misc]`
  .github/workflows/python-ci-single.yml
Labels: backport release-1.13

#2824 [python] Misc. ingest/outgest code-neaten improvements
  apis/python/pyproject.toml
  apis/python/src/tiledbsoma/io/_common.py
  apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
  apis/python/src/tiledbsoma/io/_registration/signatures.py
  apis/python/src/tiledbsoma/io/ingest.py
  apis/python/src/tiledbsoma/io/outgest.py
  apis/python/tests/test_collection.py
  apis/python/tests/test_registration_mappings.py
  apis/python/tests/test_update_dataframes.py
Labels: backport release-1.13

#2854 [python] pin `pandas-stubs>=2` during pre-commit `mypy` hook
  .github/workflows/r-ci.yml
  .pre-commit-config.yaml
  apis/python/src/tiledbsoma/_indexer.py
  apis/python/src/tiledbsoma/_types.py
Labels: backport release-1.13

#2864 [python] Offer better guidance on attribute names with `.`
  apis/python/src/tiledbsoma/_query_condition.py
  apis/python/tests/test_query_condition.py
Labels: backport release-1.13

#2866 [r] Expose `tiledb_timestamp` parameter to `$reopen()`
  .github/workflows/libtiledb-ci.yml
  .github/workflows/pkgdown.yaml
  .github/workflows/python-ci-packaging.yml
  .github/workflows/python-ci-single.yml
  .github/workflows/python-packaging.yml
  .github/workflows/r-ci.yml
  .github/workflows/r-python-interop-testing.yml
  .github/workflows/r-valgrind.yaml
  .pre-commit-config.yaml
  apis/python/src/tiledbsoma/_indexer.py
  apis/python/src/tiledbsoma/_query_condition.py
  apis/python/src/tiledbsoma/_types.py
  apis/python/src/tiledbsoma/io/_util.py
  apis/python/src/tiledbsoma/io/ingest.py
  apis/python/src/tiledbsoma/pytiledbsoma.cc
  apis/python/tests/test_query_condition.py
  apis/r/R/TileDBObject.R
Labels: r-api

#2868 `python` Utilize Arrow schema `pa.field` nullabilities in `DataFrame.create`
  apis/python/src/tiledbsoma/soma_dataframe.cc
  apis/python/tests/test_dataframe.py
Labels: backport release-1.13

#2875 [python] Fix a comment
  apis/python/tests/test_query_condition.py
Labels: backport release-1.13

#2884 [c++] Add `dataset_type` into `SOMAExperiment` metadata
  libtiledbsoma/src/soma/soma_group.cc
  libtiledbsoma/test/unit_soma_collection.cc
  libtiledbsoma/test/unit_soma_group.cc
Labels: backport release-1.13

#2888 [c++] Fix typos in unit-test case
  Makefile
  libtiledbsoma/src/soma/soma_group.cc
  libtiledbsoma/test/unit_soma_group.cc
Labels: backport release-1.13

#2891 [c++] Remove a temporary `gdb` hook from #2888
  libtiledbsoma/test/unit_soma_group.cc
Labels: backport release-1.13

#2893 [ci] Update autocut rule for current ownership
  .github/workflows/daily-test-build-issue-template.md
Labels: backport release-1.13

#2895 [c++] Apply `ArraySchemaEvolution` to specified timestamp
  apis/python/tests/test_dataframe.py
  libtiledbsoma/src/soma/soma_array.cc
Labels: backport release-1.13

#2900 [c++] Final update for Python/R metadata typing
  apis/python/src/tiledbsoma/common.cc
Labels: backport release-1.13

#2897 [c++] Corner-case bug in extend-enumeration logic
  apis/python/tests/test_dataframe.py
  libtiledbsoma/src/soma/soma_array.cc
Labels: backport release-1.13

#2929 [r] Expose timestamp ranges for libtiledbsoma
  apis/r/DESCRIPTION
  apis/r/NEWS.md
  apis/r/R/SOMAArrayBase.R
  apis/r/R/SOMADataFrame.R
  apis/r/R/SOMADenseNDArray.R
  apis/r/R/SOMASparseNDArray.R
  apis/r/R/TileDBArray.R
  apis/r/R/TileDBObject.R
  apis/r/R/utils.R
  apis/r/man/TileDBObject.Rd
  apis/r/tests/testthat/test-SOMASparseNDArray.R
  apis/r/tests/testthat/test-Timestamps.R
Labels: r-api

#2930 [r] Use cached timestamp in `$create()` and `$write()`
  apis/r/DESCRIPTION
  apis/r/NEWS.md
  apis/r/R/Factory.R
  apis/r/R/SOMAArrayBase.R
  apis/r/R/SOMADataFrame.R
  apis/r/R/SOMANDArrayBase.R
  apis/r/R/SOMASparseNDArray.R
  apis/r/R/TileDBArray.R
  apis/r/man/SOMADataFrame.Rd
  apis/r/man/SOMANDArrayBase.Rd
  apis/r/man/TileDBArray.Rd
  apis/r/tests/testthat/test-Timestamps.R
Labels: r-api
