Repository single-cell-data/TileDB-SOMA, pull requests merged in 2024-03, with the labels that each got.

#2181 [python] Drop support for Python 3.7
  .github/workflows/python-ci-full.yml
  .github/workflows/python-ci-minimal.yml
  apis/python/setup.py
  apis/python/tests/test_soma_array.py
Labels: backport release-1.7, backport release-1.8

#2194 Fix race condition (GitHub issue upcoming)
  apis/python/src/tiledbsoma/_dataframe.py
Labels: backport release-1.7, backport release-1.8

#2201 [r] Call array schema evolution after loop setting up enums
  apis/r/R/SOMADataFrame.R
Labels: backport release-1.7, backport release-1.8

#2200 [python] Fix a lint fail on `main`
  apis/python/src/tiledbsoma/_dataframe.py
Labels: backport release-1.7, backport release-1.8

#2207 [ci] Updated hard-coded core version in another file
  .github/workflows/python-so-copying.yml
  scripts/update-tiledb-version.py
Labels: backport release-1.7, backport release-1.8

#2221 [python] Fix and test `setup.py` flags to external shared objects
  .github/workflows/python-so-copying.yml
  apis/python/setup.py
Labels: backport release-1.7, backport release-1.8

#2257 [r/ci] Set `options(pkgType = "binary")` for MacOS
  .github/workflows/r-ci.yml
  apis/r/tools/install_missing_deps.R
Labels: r-api, ci

#2278 [python/ci] Complete 3.8 -> 3.11 work
  .github/workflows/python-packaging.yml
Labels: backport release-1.8

#2283 [python] Fix an ingestion corner case with empty chunks
  apis/python/src/tiledbsoma/io/ingest.py
Labels: backport release-1.8

#2290 [python] Extract fs wrapper to util file
  apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
  apis/python/src/tiledbsoma/io/_registration/signatures.py
  apis/python/src/tiledbsoma/io/_util.py
  apis/python/src/tiledbsoma/io/ingest.py
Labels: backport release-1.8

#2258 [python] Let ingest accept `additional_metadata: dict[str, Metadatum]`
  apis/python/src/tiledbsoma/_tdb_handles.py
  apis/python/src/tiledbsoma/_tiledb_object.py
  apis/python/src/tiledbsoma/_types.py
  apis/python/src/tiledbsoma/io/ingest.py
  apis/python/tests/test_basic_anndata_io.py
  apis/python/tests/test_metadata.py
Labels: backport release-1.8

#2299 Factor `pytest.fixture`s, verify #1988
  apis/python/src/tiledbsoma/_read_iters.py
  apis/python/src/tiledbsoma/_util.py
  apis/python/tests/_util.py
  apis/python/tests/conftest.py
  apis/python/tests/test_basic_anndata_io.py
  apis/python/tests/test_experiment_query.py
  apis/python/tests/test_io.py
  apis/python/tests/test_notebook_sparse_dense.py
  apis/python/tests/test_platform_config.py
  apis/python/tests/test_registration_mappings.py
  apis/python/tests/test_registration_signatures.py
  apis/python/tests/test_update_dataframes.py
  apis/python/tests/test_update_matrix.py
Labels: backport release-1.8

#2291 Make `_util.read_h5ad` a `@contextmanager`
  apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
  apis/python/src/tiledbsoma/io/_registration/signatures.py
  apis/python/src/tiledbsoma/io/_util.py
  apis/python/src/tiledbsoma/io/ingest.py
  apis/python/tests/__init__.py
Labels: backport release-1.8

#2308 Make `test_empty_categorical_query` work with TileDB<2.21
  apis/python/tests/test_experiment_query.py
Labels: backport release-1.8

#2313 [python/ci] Pin `typeguard==4.1.5`
  .github/workflows/python-ci-single.yml
  .github/workflows/r-python-interop-testing.yml
  apis/python/requirements_dev.txt
  apis/python/setup.py
Labels: backport release-1.8

#2316 [r] Add tests for enum value filters in `SOMAExperimentAxisQuery `
  apis/r/tests/testthat/test-SOMAExperiment-query.R
Labels: r-api

#2305 [c++] Fix display of Arrow schema for enum of `bytes` datatype
  .github/workflows/python-ci-minimal.yml
  apis/python/tests/test_dataframe.py
  libtiledbsoma/src/utils/arrow_adapter.cc
  libtiledbsoma/src/utils/arrow_adapter.h
Labels: backport release-1.8

#2326 [python/ci] Typofix from #2305
  .github/workflows/python-ci-minimal.yml
Labels: backport release-1.8

#2314 [python/ci] `typeguard==4.2.1`, make `requirements_dev.txt` canonical
  .github/workflows/python-ci-single.yml
  .github/workflows/r-python-interop-testing.yml
  apis/python/requirements_dev.txt
  apis/python/setup.py
  apis/python/src/tiledbsoma/_collection.py
  apis/python/src/tiledbsoma/_factory.py
  apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
Labels: backport release-1.8, backport release-1.9

#2339 [python/ci] Unbreak wheel builds
  apis/python/MANIFEST.in
Labels: backport release-1.9

#2344 Add back deprecated function `tiledbsoma_build_index`
  apis/python/src/tiledbsoma/__init__.py
  apis/python/src/tiledbsoma/_indexer.py
Labels: backport release-1.8, backport release-1.9

#2286 [python] Remove no-longer-necessary `_query_condition` import
  apis/python/tests/__init__.py
Labels: backport release-1.8

#2351 [r] Add `obsm`, `varm`, `obsp`, and `varp` to `SOMAExperimentAxisQuery`
  apis/r/DESCRIPTION
  apis/r/NEWS.md
  apis/r/R/SOMAExperimentAxisQuery.R
  apis/r/man/SOMAExperimentAxisQuery.Rd
  apis/r/tests/testthat/test-SOMAExperiment-query-m-p.R
Labels: r-api, r-python-parity

#2350 [c++/python] Add `soma_type` argument for `SOMAObject::open`
  apis/python/src/tiledbsoma/_collection.py
  apis/python/src/tiledbsoma/_tdb_handles.py
  apis/python/src/tiledbsoma/_tiledb_array.py
  apis/python/src/tiledbsoma/_tiledb_object.py
  apis/python/src/tiledbsoma/soma_object.cc
  libtiledbsoma/src/soma/soma_object.cc
  libtiledbsoma/src/soma/soma_object.h
Labels: blocker, backport release-1.8, backport release-1.9
