Repository single-cell-data/TileDB-SOMA, pull requests merged in 2025-01, with the labels that each got.

#3525 [python] Fix casting bug in `IntIndexer`
  apis/python/src/tiledbsoma/_indexer.py
  apis/python/tests/test_indexer.py
Labels: backport release-1.15

#3526 [python] Unpin `scipy`
  apis/python/setup.py
Labels: backport release-1.15

#3529 [c++] Bump `spdlog` to 1.15 and remove patch
  libtiledbsoma/cmake/Modules/FindSpdlog_EP.cmake
  libtiledbsoma/cmake/patches/spdlog.patch
Labels: backport release-1.15

#3530 [c++] When a group has no type info, say its name
  libtiledbsoma/src/soma/soma_object.cc
Labels: backport release-1.15

#3538 [python] Account for missing end-rows in shape-upgrader
  apis/python/src/tiledbsoma/io/shaping.py
Labels: backport release-1.15

#3539 [c++] Show which coordinate is out of range in `fastercsx` error messages
  libtiledbsoma/src/utils/fastercsx.h
Labels: backport release-1.15

#3543 [python] Implement `read`, `seek`, and `tell` for `SOMAVFSFilebuf`
  apis/python/src/tiledbsoma/soma_vfs.cc
Labels: backport release-1.15

#3544 [C++] Fix `ManagedQuery` segv: ctor/dtor order fix
  apis/python/tests/test_sparse_nd_array.py
  libtiledbsoma/src/soma/managed_query.cc
  libtiledbsoma/src/soma/managed_query.h
  libtiledbsoma/src/soma/soma_array.h
Labels: backport release-1.15

#3537 [python] Add region columns and metadata to SpatialData
  apis/python/src/tiledbsoma/_query.py
  apis/python/src/tiledbsoma/io/spatial/outgest.py
  apis/python/tests/test_experiment_query_spatial.py
Labels: backport release-1.15

#3553 [python] Release GIL in VFS bindings
  apis/python/src/tiledbsoma/soma_vfs.cc
Labels: backport release-1.15

#3565 [python] Throw error in `SOMAVFSFilebuf.open` on file-not-found
  apis/python/src/tiledbsoma/soma_vfs.cc
  apis/python/tests/test_basic_anndata_io.py
Labels: backport release-1.15

#3567 [c++] Handle add/drop/re-add of enumerated types
  apis/python/tests/test_update_dataframes.py
  libtiledbsoma/src/soma/soma_dataframe.cc
Labels: backport release-1.15

#3554 [python] Merge `_axisp_get_array` and `_axism_get_array` into a single function
  apis/python/src/tiledbsoma/_query.py
Labels: backport release-1.15

#3563 [python] Set `soma_joinid` to always be an index column in the `PointCloudDataFrame` class
  apis/python/notebooks/tutorial_spatial.ipynb
  apis/python/src/tiledbsoma/_constants.py
  apis/python/src/tiledbsoma/_multiscale_image.py
  apis/python/src/tiledbsoma/_point_cloud_dataframe.py
  apis/python/src/tiledbsoma/io/spatial/ingest.py
  apis/python/tests/test_basic_spatialdata_io.py
  apis/python/tests/test_experiment_query_spatial.py
  apis/python/tests/test_export_point_cloud_dataframe.py
  apis/python/tests/test_point_cloud_dataframe.py
Labels: backport release-1.15

#3573 [python] Fix search in `readthedocs`
  doc/requirements_doc.txt
  doc/source/conf.py
Labels: backport release-1.15

#3557 [python] Remove `AxisName.getattr_from` from `ExperimentAxisQuery`
  apis/python/src/tiledbsoma/_query.py
  apis/python/tests/test_experiment_query.py
Labels: backport release-1.15

#3578 [python] More `readthedocs` search fix
  doc/requirements_doc.txt
Labels: backport release-1.15

#3583 [python] On is-not-context error, show type
  apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
Labels: backport release-1.15

#3582 [python] Pass more context in `io/shaping.py`
  apis/python/src/tiledbsoma/io/shaping.py
Labels: backport release-1.15

#3588 [python] Make `region_key` a categorical when exporting to SpatialData
  apis/python/src/tiledbsoma/_query.py
Labels: backport release-1.15

#3591 [python] Update copyright header in `*.py` source files
  apis/python/src/tiledbsoma/__init__.py
  apis/python/src/tiledbsoma/_arrow_types.py
  apis/python/src/tiledbsoma/_collection.py
  apis/python/src/tiledbsoma/_common_nd_array.py
  apis/python/src/tiledbsoma/_constants.py
  apis/python/src/tiledbsoma/_dataframe.py
  apis/python/src/tiledbsoma/_dense_nd_array.py
  apis/python/src/tiledbsoma/_eager_iter.py
  apis/python/src/tiledbsoma/_exception.py
  apis/python/src/tiledbsoma/_experiment.py
  apis/python/src/tiledbsoma/_factory.py
  apis/python/src/tiledbsoma/_fastercsx.py
  apis/python/src/tiledbsoma/_funcs.py
  apis/python/src/tiledbsoma/_general_utilities.py
  apis/python/src/tiledbsoma/_geometry_dataframe.py
  apis/python/src/tiledbsoma/_indexer.py
  apis/python/src/tiledbsoma/_measurement.py
  apis/python/src/tiledbsoma/_multiscale_image.py
  apis/python/src/tiledbsoma/_point_cloud_dataframe.py
  apis/python/src/tiledbsoma/_query.py
  apis/python/src/tiledbsoma/_query_condition.py
  apis/python/src/tiledbsoma/_read_iters.py
  apis/python/src/tiledbsoma/_scene.py
  apis/python/src/tiledbsoma/_soma_array.py
  apis/python/src/tiledbsoma/_soma_group.py
  apis/python/src/tiledbsoma/_soma_object.py
  apis/python/src/tiledbsoma/_sparse_nd_array.py
  apis/python/src/tiledbsoma/_spatial_dataframe.py
  apis/python/src/tiledbsoma/_spatial_util.py
  apis/python/src/tiledbsoma/_tdb_handles.py
  apis/python/src/tiledbsoma/_types.py
  apis/python/src/tiledbsoma/_util.py
  apis/python/src/tiledbsoma/eta.py
  apis/python/src/tiledbsoma/experiment_query.py
  apis/python/src/tiledbsoma/io/__init__.py
  apis/python/src/tiledbsoma/io/_common.py
  apis/python/src/tiledbsoma/io/_registration/__init__.py
  apis/python/src/tiledbsoma/io/_registration/ambient_label_mappings.py
  apis/python/src/tiledbsoma/io/_registration/id_mappings.py
  apis/python/src/tiledbsoma/io/_registration/signatures.py
  apis/python/src/tiledbsoma/io/_util.py
  apis/python/src/tiledbsoma/io/conversions.py
  apis/python/src/tiledbsoma/io/ingest.py
  apis/python/src/tiledbsoma/io/outgest.py
  apis/python/src/tiledbsoma/io/shaping.py
  apis/python/src/tiledbsoma/io/spatial/__init__.py
  apis/python/src/tiledbsoma/io/spatial/_util.py
  apis/python/src/tiledbsoma/io/spatial/_xarray_backend.py
  apis/python/src/tiledbsoma/io/spatial/ingest.py
  apis/python/src/tiledbsoma/io/spatial/outgest.py
  apis/python/src/tiledbsoma/io/update_uns.py
  apis/python/src/tiledbsoma/logging.py
  apis/python/src/tiledbsoma/options/__init__.py
  apis/python/src/tiledbsoma/options/_soma_tiledb_context.py
  apis/python/src/tiledbsoma/options/_tiledb_create_write_options.py
  apis/python/src/tiledbsoma/stats.py
Labels: backport release-1.15

#3586 [python] Change `from_visium` to create `obs` presence matrix by default
  apis/python/notebooks/tutorial_spatial.ipynb
  apis/python/src/tiledbsoma/io/spatial/ingest.py
Labels: backport release-1.15

#3597 [python] Update warning on unsupported version
  apis/python/src/tiledbsoma/_factory.py
Labels: backport release-1.15

#3598 [r] [CI] Use binaries for packages on macOS
  .github/workflows/r-ci.yml
  apis/r/DESCRIPTION
Labels: r-api, ci, backport release-1.15

#3595 [python] Add spatial I/O functions to readthedocs
  doc/source/python-tiledbsoma-experimentaxisquery.rst
  doc/source/python-tiledbsoma-io-spatial.rst
Labels: backport release-1.15

#3594 [c++] Remove an unused-variable warning
  libtiledbsoma/test/unit_soma_column.cc
Labels: backport release-1.15

#3605 [python] Fix rendering of spatial docs
  doc/source/python-api.rst
  doc/source/python-tiledbsoma-io-spatial.rst
Labels: backport release-1.15

#3608 [python] Iterate on spatial + readthedocs
  doc/requirements_doc.txt
Labels: backport release-1.15

#3614 [c++] Remove some compiler warnings
  apis/python/src/tiledbsoma/reindexer.cc
  apis/python/src/tiledbsoma/soma_object.cc
Labels: backport release-1.15

#3620 [c++] Fix some build errors for Docker
  libtiledbsoma/src/soma/soma_dataframe.cc
  libtiledbsoma/src/utils/fastercsx.h
Labels: backport release-1.15

#3634 [python] Add spatial transforms to readthedocs
  doc/source/python-tiledbsoma-affine-transform.rst
  doc/source/python-tiledbsoma-identity-transform.rst
  doc/source/python-tiledbsoma-scale-transform.rst
  doc/source/python-tiledbsoma-uniform-scale-transform.rst
  doc/source/python-tiledbsoma.rst
Labels: backport release-1.15

#3651 [python] Add missing `MultiscaleImage` methods to docs
  doc/source/python-tiledbsoma-multiscaleimage.rst
Labels: backport release-1.15

#3653 [python] Fix readback of some older-style metadata
  apis/python/src/tiledbsoma/common.cc
Labels: backport release-1.15

#3652 [r] Use S3 method dispatch on `integer64`
  apis/r/DESCRIPTION
  apis/r/NAMESPACE
  apis/r/NEWS.md
  apis/r/R/BlockwiseIter.R
  apis/r/R/CoordsStrider.R
  apis/r/R/SOMANDArrayBase.R
  apis/r/R/TileDBArray.R
  apis/r/R/utils-arrow.R
  apis/r/R/write_soma.R
  apis/r/man/SOMADataFrame.Rd
  apis/r/man/SOMANDArrayBase.Rd
  apis/r/tests/testthat/helper-test-data.R
  apis/r/tests/testthat/helper-test-soma-objects.R
  apis/r/tests/testthat/test-00-utils.R
  apis/r/tests/testthat/test-06-SOMADataFrame.R
  apis/r/tests/testthat/test-06-SOMADenseNDArray.R
  apis/r/tests/testthat/test-06-SOMASparseNDArray.R
  apis/r/tests/testthat/test-10-SOMAArrayReader-Iterated.R
  apis/r/tests/testthat/test-11-shape.R
Labels: r-api
