Repository single-cell-data/TileDB-SOMA, pull requests merged in 2025-06, with the labels that each got.

#4101 [r] [ci] Use pak-release instead of pak-devel for R dependencies
  .github/workflows/r-ci.yml
  .github/workflows/r-python-interop-testing.yml
Labels: r-api, ci

#4108 [python] skip obs axis read-back when appending known unique observations to Experiment
  apis/python/HISTORY.md
  apis/python/src/tiledbsoma/io/ingest.py
Labels: backport release-1.18

#4113 Prepare for 1.18.0rc0
  apis/python/HISTORY.md
  apis/r/DESCRIPTION
  apis/r/NEWS.md
Labels: backport release-1.18

#4115 Update C++ exists methods to use SOMAArray _exists method
  libtiledbsoma/src/soma/soma_array.cc
  libtiledbsoma/src/soma/soma_array.h
  libtiledbsoma/src/soma/soma_dataframe.cc
  libtiledbsoma/src/soma/soma_dataframe.h
  libtiledbsoma/src/soma/soma_dense_ndarray.cc
  libtiledbsoma/src/soma/soma_dense_ndarray.h
  libtiledbsoma/src/soma/soma_geometry_dataframe.cc
  libtiledbsoma/src/soma/soma_geometry_dataframe.h
  libtiledbsoma/src/soma/soma_point_cloud_dataframe.cc
  libtiledbsoma/src/soma/soma_point_cloud_dataframe.h
  libtiledbsoma/src/soma/soma_sparse_ndarray.cc
  libtiledbsoma/src/soma/soma_sparse_ndarray.h
  libtiledbsoma/test/unit_soma_dense_ndarray.cc
Labels: backport release-1.18

#4121 [python] Check for null bytes in column name
  apis/python/src/tiledbsoma/_dataframe.py
Labels: backport release-1.18

#4102 [ci] Update GH actions in `backport.yml`
  .github/workflows/backport.yml
Labels: ci

#4145 [ci] Run `backport.yml` only on backport-labeled PRs
  .github/workflows/backport.yml
Labels: ci

#4144 [r/docs] Update missing docs
  apis/r/DESCRIPTION
  apis/r/man/SOMAArrayBase.Rd
  apis/r/man/SOMACollectionBase.Rd
  apis/r/man/SOMAObject.Rd
Labels: documentation, r-api
